"""Poetry is one exact repository build input.

``[tool.poetry].requires-poetry`` owns the version.  The committed lock and the
hash-locked CI/Docker bootstrap are derived evidence and must not drift from
it.  These checks intentionally read the generator inputs as well as their
output so a future regeneration cannot quietly reinstate a second version.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
EXACT_VERSION = re.compile(r"[0-9]+(?:\.[0-9]+){2}")


def _sole_match(pattern: str, body: str, surface: str) -> str:
    matches = re.findall(pattern, body, re.MULTILINE)
    assert len(matches) == 1, f"{surface} must declare exactly one Poetry pin"
    return matches[0]


def _repository_versions() -> dict[str, str]:
    project = tomllib.loads((REPO / "pyproject.toml").read_text(encoding="utf-8"))
    lock = (REPO / "poetry.lock").read_text(encoding="utf-8")
    bootstrap = (REPO / ".github" / "bootstrap" / "poetry-requirements.txt").read_text(
        encoding="utf-8"
    )
    generator = (REPO / ".github" / "bootstrap" / "generate.py").read_text(
        encoding="utf-8"
    )
    regenerate = (REPO / ".github" / "bootstrap" / "regenerate.sh").read_text(
        encoding="utf-8"
    )

    return {
        "pyproject.toml": project["tool"]["poetry"]["requires-poetry"],
        "poetry.lock": _sole_match(
            r"^# This file is automatically @generated by Poetry ([^ ]+) ",
            lock,
            "poetry.lock generator header",
        ),
        "bootstrap record": _sole_match(
            r"^# Pinned installer: poetry==([^\s]+)$",
            bootstrap,
            "bootstrap generator record",
        ),
        "bootstrap requirement": _sole_match(
            r"^poetry==([^\s\\]+)(?:\s+\\)?$",
            bootstrap,
            "bootstrap requirement",
        ),
        "bootstrap generator": _sole_match(
            r"^POETRY = sys\.argv\[1\] if len\(sys\.argv\) > 1 "
            r'else "poetry==([^\"]+)"$',
            generator,
            "bootstrap generator default",
        ),
        "bootstrap regeneration": _sole_match(
            r'^POETRY_PIN="\$\{1:-poetry==([^}]+)\}"$',
            regenerate,
            "bootstrap regeneration default",
        ),
    }


def _drift(versions: dict[str, str]) -> list[str]:
    wanted = versions["pyproject.toml"]
    if not isinstance(wanted, str) or EXACT_VERSION.fullmatch(wanted) is None:
        return [
            "pyproject.toml [tool.poetry].requires-poetry must be one exact "
            f"X.Y.Z version, not {wanted!r}"
        ]
    return [
        f"{surface} uses Poetry {actual}; pyproject.toml requires {wanted}"
        for surface, actual in versions.items()
        if surface != "pyproject.toml" and actual != wanted
    ]


def test_every_poetry_surface_matches_the_project_owned_exact_pin() -> None:
    versions = _repository_versions()
    assert _drift(versions) == []


def test_the_guard_is_sensitive_to_each_derived_surface_and_a_range() -> None:
    coherent = {
        "pyproject.toml": "2.4.1",
        "poetry.lock": "2.4.1",
        "bootstrap record": "2.4.1",
        "bootstrap requirement": "2.4.1",
        "bootstrap generator": "2.4.1",
        "bootstrap regeneration": "2.4.1",
    }
    assert _drift(coherent) == []

    for surface in set(coherent) - {"pyproject.toml"}:
        drifted = coherent | {surface: "2.3.1"}
        assert _drift(drifted) == [
            f"{surface} uses Poetry 2.3.1; pyproject.toml requires 2.4.1"
        ]

    ranged = coherent | {"pyproject.toml": ">=2.4"}
    assert "must be one exact X.Y.Z version" in _drift(ranged)[0]
